# fly.toml app configuration file generated for axionchamber on 2023-05-22T13:24:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "axionchamber"
primary_region = "sea"

# [http_service]
#   internal_port = 3000
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
  
  [[services.ports]]
    handlers = ["http"]
    port = "80"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
